---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-prometheus
  labels:
    app: prometheus
spec:
  capacity:
    storage: 5Gi   # 根据业务量，建议预留更大，比如50Gi或以上
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /mnt/mmban/prometheus-data
    type: DirectoryOrCreate
  claimRef:
    kind: PersistentVolumeClaim
    namespace: monitoring
    name: prometheus-data-pvc
    apiVersion: v1
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: monitoring
          operator: In
          values:
          - "true"
