---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-postgresql
  labels:
    app: postgresql
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /mnt/mmban/postgresql
    type: DirectoryOrCreate
  claimRef:
    kind: PersistentVolumeClaim
    namespace: devops
    name: postgresql-data-pvc
    apiVersion: v1
