---
apiVersion: v1
kind: Secret
metadata:
  name: gitlab
  namespace: devops
type: Opaque
data:
  db_pass: MXFhekBXU1gK 
  db_user: Z2l0bGFi
  db_name: Z2l0bGFiX3Byb2R1Y3Rpb24=
  initial_root_password: MXFhekBXU1gK
