---
apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
  namespace: devops
data:
  redis-config: |-
    save ""
    dir /data
    port 6379
    bind 0.0.0.0
    appendonly yes
    maxmemory-policy volatile-lru
