---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  namespace: devops
  labels:
    app: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      enableServiceLinks: false
      nodeSelector:
        redis: "true"
      containers:
        - name: redis
          image: registry.cn-guangzhou.aliyuncs.com/kubecy/redis:6.2.18
          imagePullPolicy: IfNotPresent
          command:
            - "/usr/local/bin/redis-server"
          args:
            - /etc/redis/redis.conf
          ports:
            - containerPort: 6379
              name: redis
          livenessProbe:
            exec:
              command:
              - redis-cli
              - ping
            initialDelaySeconds: 30
            timeoutSeconds: 5
          readinessProbe:
            exec:
              command:
              - redis-cli
              - ping
            initialDelaySeconds: 5
            timeoutSeconds: 1
          volumeMounts:
            - name: redis-storage
              mountPath: "/data"
              readOnly: false
            - name: config
              mountPath: "/etc/redis"
          resources:
            limits:
              memory: 4Gi
              cpu: "200m"
            requests:
              memory: 1Gi
              cpu: "10m"
      volumes:
        - name: redis-storage
          persistentVolumeClaim:
            claimName: redis-data-pvc
        - name: config
          configMap:
            name: redis-config
            items:
              - key: redis-config
                path: redis.conf
