apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: es-cluster
  namespace: logging-prod  # 专用日志命名空间
  labels:
    app: elasticsearch
    env: production
    compliance: pci-dss  # PCI-DSS 合规标识
spec:
  serviceName: elasticsearch-ha  # 高可用服务名
  replicas: 3
  podManagementPolicy: Parallel  # 加速初始化过程
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      partition: 0  # 可控滚动更新
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
        role: data  # 明确节点角色
        compliance: pci-dss
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9114"
        prometheus.io/path: "/metrics"
        vault.security.bank.com/tls: "elasticsearch-certs"  # 证书自动注入注解
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000
        seccompProfile:
          type: RuntimeDefault  # 启用seccomp
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values: ["elasticsearch"]
              topologyKey: "kubernetes.io/hostname"
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              preference:
                matchExpressions:
                  - key: dedicated
                    operator: In
                    values: ["logging"]  # 专用日志节点调度
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: topology.kubernetes.io/zone
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app: elasticsearch  # 跨可用区分布
      containers:
      - name: elasticsearch
        image: registry.magedu.com/elastic/elasticsearch:7.17.7-ik
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: "4"  # 与物理核绑定
            memory: "8Gi"
          requests:
            cpu: "2"
            memory: "4Gi"
        ports:
        - containerPort: 9200
          name: rest
          protocol: TCP
        - containerPort: 9300
          name: inter-node
          protocol: TCP
        volumeMounts:
        - name: data
          mountPath: /usr/share/elasticsearch/data
        - name: certs
          mountPath: /etc/elasticsearch/certs
          readOnly: true
        env:
          - name: cluster.name
            value: bank-prod-logs
          - name: node.name
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: discovery.seed_hosts
            value: "es-cluster-0.elasticsearch-ha,es-cluster-1.elasticsearch-ha,es-cluster-2.elasticsearch-ha"
          - name: cluster.initial_master_nodes
            value: "es-cluster-0,es-cluster-1,es-cluster-2"  # 多主节点初始化
          - name: ES_JAVA_OPTS
            value: "-Xms4g -Xmx4g -XX:ActiveProcessorCount=4"  # 精确CPU绑定
          - name: network.host
            value: "_site_"
          - name: xpack.security.enabled
            value: 'true'
          - name: xpack.security.transport.ssl.enabled
            value: 'true'
          - name: xpack.security.http.ssl.enabled
            value: 'true'
          - name: xpack.security.authc.token.enabled
            value: 'true'
          - name: xpack.security.audit.enabled
            value: 'true'  # 启用审计日志
        livenessProbe:
          httpGet:
            path: /_cluster/health
            port: 9200
            scheme: HTTPS
            httpHeaders:
              - name: Authorization
                value: "Basic $(echo -n elastic:${ES_PASSWORD} | base64)"  # 安全凭证
          initialDelaySeconds: 120  # 延长冷启动等待
          periodSeconds: 45
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /_cluster/health
            port: 9200
            scheme: HTTPS
          initialDelaySeconds: 60
          periodSeconds: 20
          successThreshold: 2

      - name: elasticsearch-exporter
        image: registry.magedu.com/prometheuscommunity/elasticsearch-exporter:v1.6.0
        args:
        - --es.uri=https://localhost:9200
        - --es.ca=/etc/elasticsearch/certs/ca.crt
        - --es.client-cert=/etc/elasticsearch/certs/tls.crt
        - --es.client-key=/etc/elasticsearch/certs/tls.key
        - --es.ssl-skip-verify=false
        - --es.timeout=20s  # 严格超时控制
        ports:
        - name: es-exporter
          containerPort: 9114
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "100m"
            memory: "128Mi"
        volumeMounts:
        - name: certs
          mountPath: /etc/elasticsearch/certs
          readOnly: true

      initContainers:
      - name: security-init
        image: registry.bank.com/security-tools:v2.1  # 行方认证镜像
        command:
          - bash
          - -c
          - |
            sysctl -w vm.max_map_count=262144
            ulimit -n 65536
            chown -R 1000:1000 /usr/share/elasticsearch/data
        securityContext:
          privileged: true
        volumeMounts:
        - name: data
          mountPath: /usr/share/elasticsearch/data

  volumeClaimTemplates:
  - metadata:
      name: data
      labels:
        app: elasticsearch
        storage-tier: platinum  # 存储分级标签
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: nfs-ssd-premium  # 高性能存储类
      resources:
        requests:
          storage: 500Gi  # 基于日志保留策略
      volumeMode: Filesystem