---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-gitlab
  labels:
    app: gitlab
spec:
  capacity:
    storage: 10Gi   # 根据业务量，建议预留更大，比如50Gi或以上
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /mnt/mmban/gitlab-data
    type: DirectoryOrCreate
  claimRef:
    kind: PersistentVolumeClaim
    namespace: devops
    name: gitlab-data-pvc
    apiVersion: v1
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: devops
          operator: In
          values:
          - "true"
