---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitlab-data-pvc
  namespace: devops
  labels:
    app: gitlab
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual     # 强烈建议补充storageClassName，绑定对应PV
  resources:
    requests:
      storage: 10Gi          
  selector:
    matchLabels:
      app: gitlab          # 精准绑定PV
  volumeName: local-gitlab # 指定volume，强绑定
  volumeMode: Filesystem 
