apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
  namespace: monitoring
data:
  alertmanager.yml: |
    global:
      resolve_timeout: 2m

    route:
      group_by: ['job', 'alertname']
      group_wait: 10s
      group_interval: 15s
      repeat_interval: 3h
      receiver: "dingtalk"

    templates:
      - "./templates/*.tmpl"

    receivers:
      - name: 'dingtalk'
        webhook_configs:
          - url: http://prometheus-webhook-dingtalk:8060/dingtalk/webhook1/send
            send_resolved: true

    inhibit_rules:
      - source_match:
          severity: critical
        target_match_re:
          severity: warning|info
      - source_match:
          severity: warning
        target_match_re:
          severity: info
        equal: ['job', 'alertname']

