apiVersion: apps/v1
kind: Deployment
metadata:
  name: demoapp-deployment
  labels:
    app: demoapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demoapp
  template:
    metadata:
      labels:
        app: demoapp
    spec:
      containers:
      - name: demoapp
        image: registry.cn-guangzhou.aliyuncs.com/kansctl/demoapp:v2.0 
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: demoapp-svc
spec:
  type: ClusterIP
  selector:
    app: demoapp
  ports:
  - port: 8080
    targetPort: 8080


---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: demoapp-ingress
spec:
  ingressClassName: nginx
  rules:
    - host: demoapp.kubecy.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: demoapp-svc
                port:
                  number: 8080
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: demoapp-gw
spec:
  gatewayClassName: traefik
  listeners:
  - protocol: HTTP
    port: 80
    name: demoapp-gw-http
    allowedRoutes:
      namespaces:
        from: All

---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: demoapp-http
spec:
  hostnames: 
  - demoapp.kubecy.com
  parentRefs:
  - name: demoapp-gw
    #sectionName: http
    kind: Gateway
  rules:
  - backendRefs:
    - name: demoapp-svc
      port: 8080
      kind: Service
    matches:
    - path:
        type: PathPrefix
        value: /
